version: '3'
services:
 app:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: app
   restart: always
   working_dir: /var/www
   volumes:
     - ./:/var/www
   networks:
     - app-network

 webserver:
   image: nginx:alpine
   container_name: webserver
   restart: always
   ports:
     - 8080:80
   volumes:
     - ./:/var/www
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   networks:
     - app-network

 db:
   image: mysql:5.7.22
   container_name: db
   restart: always
   environment:
     MYSQL_DATABASE: laravel
     MYSQL_ROOT_PASSWORD: your_mysql_root_password
   volumes:
     - dbdata:/var/lib/mysql
   networks:
     - app-network

networks:
 app-network:
   driver: bridge

volumes:
 dbdata:
   driver: local
